sipeed_tof_node:
  ros__parameters:
    # The serial device path for the ToF camera
    device: "/dev/serial/by-id/usb-SIPEED_SIPEED_Meta_Sense_Lite_202206_AA725F-if00-port0"
    
    # The frame_id for published messages
    frame_id: "tof_camera_optical_frame"

    timer_period_ms: 30
    
    # --- New Camera Configuration Parameters ---

    # Binning mode for resolution.
    # 1: 100x100, 2: 50x50, 4: 25x25
    binning: 1
    # Display mode
    # 0: all off, 1: LCD only, 2: usb only, 4: UART (and all binary combinations) 
    display_mode: 2

    # Frame rate in frames per second.
    # Range: 1 to 19
    fps: 19
    # Quantization unit in mm. 0 is the default sqrt strategy.
    # Range: 0 to 9
    quantization_unit: 0